### ISSUE TITLE
`npm install` on heroku

### ISSUE THREAD

**Issue by jonchoi** [dternyak/React-Redux-Flask#15]
how do i configure heroku/Procfile to do the equivalent of `cd static; npm install` before it starts running the flask app? thanks!

**Comment by dternyak** [comment]
This might help you https://devcenter.heroku.com/articles/nodejs-support

**Comment by jonchoi** [comment]
Thanks but it's not as simple as that. I'm trying a multi build pack approach.

it first builds the flask app since it identifies requirements.txt. but since package.json is under `/static` it's having trouble building.

what's the best practice to kick of `cd static && npm install` and then `npm start`?

can this repo deploy to heroku without any other configuration? i seem to be missing something.

**Comment by jonchoi** [comment]
Fixed by adding package.json at root:

`{ 
    "engines": {
        "node": "6.10.2",
        "npm": "4.4.4"
    },
    "scripts": {
        "postinstall": "cd static && npm --dev install && npm run build:production"
    }
}`

**Comment by Hudsonzp** [comment]
I'm having this exact same issue.  When you try to deploy to heroku, it recognizes it as a python application and completely skips installing Node, NPM, or running the build there.  As a result, you can never get the frontend to actually launch.   I tried Jon's solution above by installing a package.json in root, but it didn't seem to do anything and the heroku app still relies on requirements.txt and ignores that new package.json.  Any other thoughts?

**Comment by viatsko** [comment]
You need nodejs buildpack as well, you can achieve this by using these commands:

```sh
heroku buildpacks:set heroku/python
heroku buildpacks:add heroku/nodejs
```

package.json could be needed as well tho

**Comment by Hudsonzp** [comment]
@viatsko you rock.  That totally seemed to fix my npm/node issue.   I also saw all my packages install which is fantastic. Now I'm just having issues with any of my containers/components being recognized from the boilerplate.  Getting all sorts of weird stuff like: 

ERROR in ./src/containers/HomeContainer/index.js
remote:        Module not found: Error: Cannot resolve 'file' or 'directory' ../../components/IntroSection in /tmp/build_d95bc1f5e53719f4bd91a1a3/static/src/containers/HomeContainer
remote:        resolve file
remote:        /tmp/build_d95bc1f5e53719f4bd91a1a3/static/src/components/IntroSection doesn't exist

When I run the same build:production on my local it works no problem. For some reason it isn't taking any of these on Heroku.  If you have an answer I'm all ears!  Otherwise I'll move out of this thread and try to debug. Thanks for the help so far!

**Comment by viatsko** [comment]
That's a problem with your component - probably path should be `../components/IntroSection` instead of `../../components/IntroSection` (see ../ part)

**Comment by Hudsonzp** [comment]
To update this, seems like there is a lot more needed to be fixed to run this application successfully with heroku.  Examples include: moving all devdependencies into dependencies, setting up a new server.js "script" in package.json.  Creating a secondary package.json file at root level because heroku can't see the one tucked into static.   For now, this boilerplate is definitely not heroku ready out of the box.

**Comment by viatsko** [comment]
Well, building devDependencies is also something you can configure within heroku, see https://devcenter.heroku.com/articles/nodejs-support#devdependencies

You'll always have to tailor software to your own specific deployment method, some might prefer to have application built upfront (for which the current `master` looks logical), some wouldn't :)

**Comment by Hudsonzp** [comment]
Ya that's a good point.  I suppose I just assumed a bit too much from the readme of the repo that said "Heroku".  Once I get this thing up and running I'll report back with some tips and tricks that could maybe be dropped in there or at least a nice thread here in the issues to refer to.
